paths:
  prefix_dir: 'data'
  dataset_dir: 'dataset_16km_300_ndsi'
  machine_learning_dir: 'ML'
model:
  name: 'EfficientNet'
  freeze_parameters: False
  use_transfer_learning: False
processing:
  batch_size: 16
  batch_normalization: False
  batch_accumulation: 3
  num_epochs: 32
  use_ordinal_regression: False
  use_one_neuron_regression: False
  ordinal_regression_loss: 'MSE'
  activation_function: 'Sigmoid'
  use_weighted_loss_function: False
  use_weighted_sampler: True
  use_manual_labels: False
  optimizer: 'Adam'
  learning_rate_exp: 3
  momentum: 0.9
  use_dropout: True
  dropout_p: 0.2
  use_weight_decay: False
  weight_decay_exp: 4
output:
  output_name: 'efficientnet_v2_s_preset_3_16km_300_weighted_sampler_classification_dropout_20.pt'
  show_samples: False
  show_summary: False
