paths:
  prefix_dir: 'data'
  dataset_dir: 'dataset_manual_labels'
  machine_learning_dir: 'ML'
model:
  name: 'EfficientNet'
  freeze_parameters: False
processing:
  batch_size: 16
  batch_normalization: False
  batch_accumulation: 3
  num_epochs: 32
  use_ordinal_regression: True
  activation_function: 'Sigmoid'
  use_weighted_loss_function: True
  use_weighted_sampler: False
  use_manual_labels: False
  optimizer: 'Adam'
  learning_rate_exp: 3
  momentum: 0.9
  use_dropout: False
  dropout_p: 0.5
  use_weight_decay: False
  weight_decay_exp: 4
output:
  output_name: 'local_dummy.pt'
  show_samples: False
  show_summary: False